export interface CityCategory {
  id: string;
  name: string;
  iconName: string;
  color: string;
  description: string;
  count: number;
}

export interface CityOrganization {
  id: number;
  categoryId: string;
  name: string;
  subcategory: string;
  phone: string;
  address: string;
  hours: string;
  website?: string;
  whatsapp?: string;
  district: string;
  isEmergency?: boolean;
  importantNumber?: boolean;
  description?: string;
  lat?: number;
  lng?: number;
}

// Approximate distance based on org id (deterministic, stable across renders).
// In production this would be computed from user geolocation + org coordinates.
export function getOrgDistance(org: { id: number; district?: string }): string {
  const km = ((org.id * 37) % 55) / 10 + 0.3; // 0.3 — 5.7 км
  return `${km.toFixed(1)} км`;
}

export const cityCategories: CityCategory[] = [
  {
    id: 'emergency',
    name: 'Экстренные службы',
    iconName: 'ShieldAlert',
    color: '#FF3B30',
    description: 'Полиция, скорая, пожарные, газ',
    count: 7,
  },
  {
    id: 'transport',
    name: 'Транспорт',
    iconName: 'Car',
    color: '#007AFF',
    description: 'Аэропорт, вокзал, такси, маршрутки',
    count: 7,
  },
  {
    id: 'government',
    name: 'Госуслуги',
    iconName: 'Landmark',
    color: '#5856D6',
    description: 'МФЦ, администрация, налоговая, СФР',
    count: 7,
  },
  {
    id: 'medicine',
    name: 'Медицина',
    iconName: 'HeartPulse',
    color: '#34C759',
    description: 'Больницы, поликлиники, аптеки',
    count: 8,
  },
  {
    id: 'contacts',
    name: 'Полезные контакты',
    iconName: 'BookMarked',
    color: '#FF9500',
    description: 'Банки, отели, нотариусы, ЖКХ',
    count: 8,
  },
  {
    id: 'important',
    name: 'Важные номера',
    iconName: 'Phone',
    color: '#AF52DE',
    description: 'Единые номера экстренных служб ЧР',
    count: 8,
  },
];

export const cityOrganizations: CityOrganization[] = [
  // ── EMERGENCY ──
  {
    id: 1,
    categoryId: 'emergency',
    name: 'Полиция (дежурная часть)',
    subcategory: 'Правоохранительные органы',
    phone: '102',
    address: 'Дежурные части — по всему городу',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов полиции. При угрозе жизни или правонарушении. С мобильного — 102.',
  },
  {
    id: 2,
    categoryId: 'emergency',
    name: 'Скорая медицинская помощь',
    subcategory: 'Медицинские службы',
    phone: '103',
    address: 'Станция скорой помощи г. Грозный',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Экстренная медицинская помощь. С мобильного — 103.',
  },
  {
    id: 3,
    categoryId: 'emergency',
    name: 'Пожарно-спасательная служба',
    subcategory: 'Спасательные службы',
    phone: '101',
    address: 'Пожарно-спасательные части по всему Грозному',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов пожарных. Пожар, спасение, ликвидация аварий. С мобильного — 101.',
  },
  {
    id: 4,
    categoryId: 'emergency',
    name: 'Аварийная газовая служба',
    subcategory: 'Коммунальные аварии',
    phone: '104',
    address: 'Аварийная служба ООО «Газпром газораспределение Грозный»',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Утечка газа. Не включайте свет и электроприборы, покиньте помещение, звоните 104.',
  },
  {
    id: 5,
    categoryId: 'emergency',
    name: 'Единый номер экстренных служб',
    subcategory: 'Универсальный номер',
    phone: '112',
    address: 'Система-112 Чеченской Республики',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Единый номер вызова всех экстренных служб. Работает без SIM-карты и при нулевом балансе.',
  },
  {
    id: 6,
    categoryId: 'emergency',
    name: 'ГУ МЧС России по ЧР',
    subcategory: 'Спасательные службы',
    phone: '+7 (8712) 33-30-69',
    address: 'ул. Гаражная, 9а, Грозный',
    hours: 'Круглосуточно',
    website: 'https://95.mchs.gov.ru',
    district: 'Ленинский',
    isEmergency: true,
    description: 'Главное управление МЧС России по Чеченской Республике. Телефон доверия.',
    lat: 43.3180, lng: 45.6900,
  },
  {
    id: 7,
    categoryId: 'emergency',
    name: 'Аварийная служба водоканала',
    subcategory: 'Коммунальные аварии',
    phone: '+7 (8712) 22-25-73',
    address: 'МУП «Водоканал г. Грозного»',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Прорывы водопровода, аварии на сетях водоснабжения и канализации.',
  },

  // ── TRANSPORT ──
  {
    id: 101,
    categoryId: 'transport',
    name: 'Аэропорт «Грозный» (Северный) им. А. А. Кадырова',
    subcategory: 'Аэропорты',
    phone: '+7 (800) 250-94-95',
    address: 'Старопромысловский район, Грозный',
    hours: 'Круглосуточно',
    website: 'https://airport-grozny.ru',
    district: 'Старопромысловский',
    description: 'Международный аэропорт Грозный (GRV). Справочная по рейсам — бесплатный номер.',
    lat: 43.3883, lng: 45.6986,
  },
  {
    id: 102,
    categoryId: 'transport',
    name: 'Железнодорожный вокзал Грозный',
    subcategory: 'Железнодорожные вокзалы',
    phone: '8 (800) 775-00-00',
    address: 'ул. Орджоникидзе, 1, Грозный',
    hours: 'Круглосуточно',
    website: 'https://rzd.ru',
    district: 'Центральный',
    description: 'Поезда в Москву, Волгоград и другие города России. Единая справочная РЖД.',
    lat: 43.3110, lng: 45.6960,
  },
  {
    id: 103,
    categoryId: 'transport',
    name: 'Автовокзал «Южный»',
    subcategory: 'Автовокзалы',
    phone: '+7 (8712) 22-23-16',
    address: 'ул. Узуева, 26, Грозный',
    hours: '06:00–19:00',
    district: 'Октябрьский',
    description: 'Междугородние автобусы в города ЧР и соседние регионы Северного Кавказа.',
    lat: 43.2960, lng: 45.7050,
  },
  {
    id: 104,
    categoryId: 'transport',
    name: 'Автовокзал «Западный»',
    subcategory: 'Автовокзалы',
    phone: '+7 (8712) 29-42-24',
    address: 'ул. Ленина, 2, Грозный',
    hours: '06:00–19:00',
    district: 'Заводской',
    description: 'Автобусы западного направления: Ачхой-Мартан, Урус-Мартан, Назрань, Нальчик.',
    lat: 43.312, lng: 45.668,
  },
  {
    id: 105,
    categoryId: 'transport',
    name: 'Яндекс Go (такси)',
    subcategory: 'Такси',
    phone: '+7 (800) 600-60-07',
    address: 'По всему городу',
    hours: 'Круглосуточно',
    website: 'https://taxi.yandex.ru',
    district: 'Все районы',
    description: 'Заказ такси через приложение Яндекс Go. Работает по Грозному и пригородам.',
  },
  {
    id: 106,
    categoryId: 'transport',
    name: 'Такси «Вайнах»',
    subcategory: 'Такси',
    phone: '+7 (8712) 22-22-42',
    address: 'По всему городу',
    hours: 'Круглосуточно',
    district: 'Все районы',
    description: 'Городская служба такси Грозного. Поездки по городу и республике.',
  },
  {
    id: 107,
    categoryId: 'transport',
    name: 'Троллейбусное управление г. Грозного',
    subcategory: 'Общественный транспорт',
    phone: '+7 (8712) 22-63-44',
    address: 'ул. Маяковского, 145, Грозный',
    hours: '06:00–20:00',
    district: 'Старопромысловский',
    description: 'Городские троллейбусные и автобусные маршруты. Информация о расписании.',
    lat: 43.335, lng: 45.678,
  },

  // ── GOVERNMENT ──
  {
    id: 201,
    categoryId: 'government',
    name: 'МФЦ «Мои документы» по ЧР',
    subcategory: 'МФЦ',
    phone: '+7 (8712) 29-41-78',
    address: 'ул. им. Л. Д. Магомадова, 70, Грозный',
    hours: 'Пн-Пт 09:00–20:00, Сб 09:00–14:00',
    website: 'https://rmfc-95.ru',
    district: 'Ленинский',
    description: 'Республиканский МФЦ: паспорта, регистрация, льготы, выписки. Выдача документов: +7 (8712) 29-41-79.',
    lat: 43.3050, lng: 45.6890,
  },
  {
    id: 202,
    categoryId: 'government',
    name: 'Мэрия г. Грозного',
    subcategory: 'Городская администрация',
    phone: '+7 (8712) 22-46-91',
    address: 'пр-т им. Х. А. Исаева, 99/20, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://grozmer.ru',
    district: 'Ленинский',
    description: 'Администрация города Грозного. Обращения граждан, городские вопросы.',
    lat: 43.3212, lng: 45.6850,
  },
  {
    id: 203,
    categoryId: 'government',
    name: 'Правительство Чеченской Республики',
    subcategory: 'Региональная власть',
    phone: '+7 (8712) 22-20-15',
    address: 'Дом Правительства, ул. Гаражная, 10а, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://chechnya.gov.ru',
    district: 'Ленинский',
    description: 'Правительство ЧР. Приёмная, обращения граждан.',
    lat: 43.3178, lng: 45.6903,
  },
  {
    id: 204,
    categoryId: 'government',
    name: 'УФНС России по ЧР',
    subcategory: 'Налоговые органы',
    phone: '8 (800) 222-22-22',
    address: 'ул. С. Ш. Лорсанова, 12, Грозный',
    hours: 'Пн-Чт 09:00–18:00, Пт 09:00–16:45',
    website: 'https://www.nalog.gov.ru',
    district: 'Ленинский',
    description: 'Налоговый учёт, ИНН, декларации, регистрация ИП. Единый контакт-центр ФНС.',
    lat: 43.3175, lng: 45.6940,
  },
  {
    id: 205,
    categoryId: 'government',
    name: 'Отделение СФР по ЧР',
    subcategory: 'Социальные службы',
    phone: '8 (800) 100-00-01',
    address: 'ул. Шейха Али Митаева, 4, Грозный',
    hours: 'Пн-Чт 09:00–18:00, Пт 09:00–16:45',
    website: 'https://sfr.gov.ru/branches/chechnya/',
    district: 'Ленинский',
    description: 'Социальный фонд России: пенсии, материнский капитал, пособия и выплаты.',
    lat: 43.305, lng: 45.69,
  },
  {
    id: 206,
    categoryId: 'government',
    name: 'Портал Госуслуги',
    subcategory: 'Электронные услуги',
    phone: '8 (800) 100-70-10',
    address: 'Онлайн-сервис',
    hours: 'Круглосуточно',
    website: 'https://gosuslugi.ru',
    district: 'Все районы',
    description: 'Государственные и муниципальные услуги через интернет. Поддержка — 115 с мобильного.',
  },
  {
    id: 207,
    categoryId: 'government',
    name: 'Департамент ЖКХ мэрии г. Грозного',
    subcategory: 'Коммунальные службы',
    phone: '+7 (8712) 22-46-51',
    address: 'пр-т им. Х. А. Исаева, 99/20, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Ленинский',
    description: 'Вопросы ЖКХ: отопление, водоснабжение, дороги, благоустройство города.',
    lat: 43.3212, lng: 45.685,
  },

  // ── MEDICINE ──
  {
    id: 301,
    categoryId: 'medicine',
    name: 'Республиканская клиническая больница им. А.-Х. Кадырова',
    subcategory: 'Больницы',
    phone: '+7 (8712) 33-24-21',
    address: 'ул. Хвойная, 5, Грозный',
    hours: 'Круглосуточно',
    district: 'Октябрьский',
    description: 'Главная многопрофильная больница ЧР (ранее РКБ им. Ш. Ш. Эпендиева). Экстренная и плановая помощь.',
    lat: 43.2830, lng: 45.7080,
  },
  {
    id: 302,
    categoryId: 'medicine',
    name: 'Республиканская больница скорой помощи им. У. И. Ханбиева',
    subcategory: 'Больницы',
    phone: '+7 (8712) 29-44-01',
    address: 'ул. Айдамирова (Гудермесская), 22, Грозный',
    hours: 'Круглосуточно',
    district: 'Байсангуровский',
    description: 'Больница скорой медицинской помощи. Приёмное отделение 24/7.',
    lat: 43.318, lng: 45.712,
  },
  {
    id: 303,
    categoryId: 'medicine',
    name: 'Детская клиническая больница №2 г. Грозного',
    subcategory: 'Детские больницы',
    phone: '+7 (8712) 22-25-53',
    address: 'ул. Ионисиани, 2а, Грозный',
    hours: 'Круглосуточно',
    website: 'https://dkb2grozny.ru',
    district: 'Ленинский',
    description: 'Детская клиническая больница. Стационар и консультативный приём.',
    lat: 43.316, lng: 45.687,
  },
  {
    id: 304,
    categoryId: 'medicine',
    name: 'Городская поликлиника №1',
    subcategory: 'Поликлиники',
    phone: '+7 (8712) 22-24-40',
    address: 'ул. Дьякова, 4а, Грозный',
    hours: 'Пн-Пт 08:00–18:00, Сб 09:00–14:00',
    district: 'Ленинский',
    description: 'Первичная медицинская помощь взрослому населению. Запись через Госуслуги.',
    lat: 43.32, lng: 45.694,
  },
  {
    id: 305,
    categoryId: 'medicine',
    name: 'Республиканский клинический центр охраны здоровья матери и ребёнка',
    subcategory: 'Женское и детское здоровье',
    phone: '+7 (8712) 29-99-03',
    address: 'ул. У. Садаева (Киевская), 10, Грозный',
    hours: 'Круглосуточно',
    district: 'Ленинский',
    description: 'Роддом, перинатальный центр, женские консультации, детские отделения.',
    lat: 43.308, lng: 45.692,
  },
  {
    id: 306,
    categoryId: 'medicine',
    name: 'Стоматологический центр г. Грозного',
    subcategory: 'Стоматологии',
    phone: '+7 (8712) 29-66-77',
    address: 'ул. Державина, 285, Грозный',
    hours: 'Пн-Сб 08:00–20:00',
    website: 'https://sc-grozny.ru',
    district: 'Заводской',
    description: 'Государственный стоматологический центр: лечение, протезирование, детский приём.',
    lat: 43.328, lng: 45.672,
  },
  {
    id: 307,
    categoryId: 'medicine',
    name: 'Республиканский онкологический диспансер',
    subcategory: 'Диспансеры',
    phone: '+7 (8712) 22-38-72',
    address: 'ул. Санаторная, 1, Грозный',
    hours: 'Пн-Пт 08:00–17:00',
    district: 'Старопромысловский',
    description: 'Диагностика и лечение онкологических заболеваний. Приём по направлению.',
    lat: 43.336, lng: 45.68,
  },
  {
    id: 308,
    categoryId: 'medicine',
    name: 'Горячая линия Минздрава ЧР',
    subcategory: 'Справочные',
    phone: '+7 (963) 597-62-48',
    address: 'Министерство здравоохранения ЧР, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Все районы',
    description: 'Вопросы качества и доступности медицинской помощи в Чеченской Республике.',
  },

  // ── CONTACTS ──
  {
    id: 401,
    categoryId: 'contacts',
    name: 'Cosmos Selection Грозный Сити Отель 5*',
    subcategory: 'Отели',
    phone: '+7 (8712) 22-11-11',
    address: 'МФК «Грозный-Сити», наб. р. Сунжи, Грозный',
    hours: 'Круглосуточно',
    website: 'https://groznycity.cosmosgroup.ru',
    district: 'Центральный',
    description: 'Пятизвёздочный отель в комплексе «Грозный-Сити» с видом на город.',
    lat: 43.3115, lng: 45.6890,
  },
  {
    id: 402,
    categoryId: 'contacts',
    name: 'Отель «Тийналла»',
    subcategory: 'Отели',
    phone: '+7 (8712) 29-63-33',
    address: 'ул. Умара Димаева, 11, Грозный',
    hours: 'Круглосуточно',
    website: 'http://tiynalla.ru',
    district: 'Центральный',
    description: 'Отель в центре Грозного рядом с мечетью «Сердце Чечни».',
    lat: 43.3168, lng: 45.687,
  },
  {
    id: 403,
    categoryId: 'contacts',
    name: 'Сбербанк — офисы в Грозном',
    subcategory: 'Банки',
    phone: '8 (800) 555-55-50',
    address: 'пр-т им. А. А. Кадырова, 3/25, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://sberbank.ru',
    district: 'Центральный',
    description: 'Кредиты, вклады, переводы. Единая справочная — 900 с мобильного.',
    lat: 43.3125, lng: 45.6885,
  },
  {
    id: 404,
    categoryId: 'contacts',
    name: 'Россельхозбанк — офис в Грозном',
    subcategory: 'Банки',
    phone: '8 (800) 100-01-00',
    address: 'ул. Кадырова (Гудермесская), Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://rshb.ru',
    district: 'Байсангуровский',
    description: 'Кредитование, вклады, обслуживание бизнеса и сельхозпроизводителей.',
    lat: 43.318, lng: 45.708,
  },
  {
    id: 405,
    categoryId: 'contacts',
    name: 'Нотариальная палата Чеченской Республики',
    subcategory: 'Нотариусы',
    phone: '+7 (8712) 22-60-95',
    address: 'пр-т Кадырова, 53, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://95.notariat.ru',
    district: 'Центральный',
    description: 'Реестр нотариусов республики, контакты нотариальных контор Грозного.',
    lat: 43.311, lng: 45.6875,
  },
  {
    id: 406,
    categoryId: 'contacts',
    name: 'АО «Чеченэнерго» (справочная)',
    subcategory: 'ЖКХ и энергетика',
    phone: '8 (800) 220-02-20',
    address: 'Старопромысловское шоссе, 6, Грозный',
    hours: 'Круглосуточно',
    district: 'Все районы',
    description: 'Отключения электроэнергии, аварии на сетях, вопросы энергоснабжения.',
    lat: 43.33, lng: 45.678,
  },
  {
    id: 407,
    categoryId: 'contacts',
    name: 'Почта России — главпочтамт Грозного',
    subcategory: 'Почта',
    phone: '8 (800) 100-00-00',
    address: 'пр-т им. В. В. Путина, 9, Грозный',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–18:00',
    website: 'https://pochta.ru',
    district: 'Центральный',
    description: 'Отправка и получение писем и посылок, оплата услуг, подписка.',
    lat: 43.3172, lng: 45.6935,
  },
  {
    id: 408,
    categoryId: 'contacts',
    name: 'Национальный музей Чеченской Республики',
    subcategory: 'Культура',
    phone: '+7 (8712) 22-24-58',
    address: 'пр-т им. В. В. Путина, 1б, Грозный',
    hours: 'Вт-Вс 10:00–18:00',
    district: 'Центральный',
    description: 'Главный музей республики: история, этнография, искусство Чечни.',
    lat: 43.318, lng: 45.6945,
  },

  // ── IMPORTANT NUMBERS ──
  {
    id: 501,
    categoryId: 'important',
    name: 'Единый экстренный (с мобильного)',
    subcategory: 'Экстренные',
    phone: '112',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Работает при нулевом балансе и без SIM-карты. Полиция, скорая, пожарные, газ.',
  },
  {
    id: 502,
    categoryId: 'important',
    name: 'Полиция',
    subcategory: 'Экстренные',
    phone: '102',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Вызов полиции.',
  },
  {
    id: 503,
    categoryId: 'important',
    name: 'Скорая помощь',
    subcategory: 'Экстренные',
    phone: '103',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Экстренная медицинская помощь.',
  },
  {
    id: 504,
    categoryId: 'important',
    name: 'Пожарная охрана',
    subcategory: 'Экстренные',
    phone: '101',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Пожар, спасение людей.',
  },
  {
    id: 505,
    categoryId: 'important',
    name: 'Аварийная газовая служба',
    subcategory: 'Экстренные',
    phone: '104',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Утечка газа.',
  },
  {
    id: 506,
    categoryId: 'important',
    name: 'Телефон доверия ГУ МЧС по ЧР',
    subcategory: 'Спасательные службы',
    phone: '+7 (8712) 33-30-69',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Чрезвычайные ситуации, жалобы и обращения в МЧС по Чеченской Республике.',
  },
  {
    id: 507,
    categoryId: 'important',
    name: 'Детский телефон доверия (бесплатный)',
    subcategory: 'Психологическая помощь',
    phone: '8 (800) 2000-122',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    description: 'Бесплатная анонимная психологическая помощь для детей и родителей.',
  },
  {
    id: 508,
    categoryId: 'important',
    name: 'Горячая линия Минздрава ЧР',
    subcategory: 'Здоровье',
    phone: '+7 (963) 597-62-48',
    address: '',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Все районы',
    importantNumber: true,
    description: 'Вопросы качества медицинской помощи в Чеченской Республике.',
  },
];

export const districts = [
  'Все районы',
  'Центральный',
  'Ленинский',
  'Заводской',
  'Октябрьский',
  'Байсангуровский',
  'Старопромысловский',
  'Шейх-Мансуровский',
  'Ахматовский',
];
