export interface CityCategory {
  id: string;
  name: string;
  iconName: string;
  color: string;
  description: string;
  count: number;
}

export interface CityOrganization {
  id: number;
  categoryId: string;
  name: string;
  subcategory: string;
  phone: string;
  address: string;
  hours: string;
  website?: string;
  whatsapp?: string;
  district: string;
  isEmergency?: boolean;
  importantNumber?: boolean;
  description?: string;
}

export const cityCategories: CityCategory[] = [
  {
    id: 'emergency',
    name: 'Экстренные службы',
    iconName: 'ShieldAlert',
    color: '#FF3B30',
    description: 'Полиция, скорая, пожарные, газ',
    count: 6,
  },
  {
    id: 'transport',
    name: 'Транспорт',
    iconName: 'Car',
    color: '#007AFF',
    description: 'Аэропорт, вокзал, такси, маршрутки',
    count: 7,
  },
  {
    id: 'government',
    name: 'Госуслуги',
    iconName: 'Landmark',
    color: '#5856D6',
    description: 'МФЦ, администрация, налоговая, ПФР',
    count: 7,
  },
  {
    id: 'medicine',
    name: 'Медицина',
    iconName: 'HeartPulse',
    color: '#34C759',
    description: 'Больницы, поликлиники, аптеки',
    count: 8,
  },
  {
    id: 'contacts',
    name: 'Полезные контакты',
    iconName: 'BookMarked',
    color: '#FF9500',
    description: 'Банки, АЗС, нотариусы, эвакуаторы',
    count: 9,
  },
  {
    id: 'important',
    name: 'Важные номера',
    iconName: 'Phone',
    color: '#AF52DE',
    description: 'Единые номера экстренных служб ЧР',
    count: 8,
  },
];

export const cityOrganizations: CityOrganization[] = [
  // ── EMERGENCY ──
  {
    id: 1,
    categoryId: 'emergency',
    name: 'Полиция',
    subcategory: 'Правоохранительные органы',
    phone: '102',
    address: 'Дежурная часть — по всему городу',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов полиции. При угрозе жизни или правонарушении.',
  },
  {
    id: 2,
    categoryId: 'emergency',
    name: 'Скорая помощь',
    subcategory: 'Медицинские службы',
    phone: '103',
    address: 'Станция скорой помощи г. Грозный',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Экстренная медицинская помощь.',
  },
  {
    id: 3,
    categoryId: 'emergency',
    name: 'Пожарная охрана',
    subcategory: 'Спасательные службы',
    phone: '101',
    address: 'Пожарные части по всему Грозному',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов пожарных. Пожар, спасение, ликвидация аварий.',
  },
  {
    id: 4,
    categoryId: 'emergency',
    name: 'Аварийная газовая служба',
    subcategory: 'Коммунальные аварии',
    phone: '104',
    address: 'Аварийная служба «Чеченгаз»',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Утечка газа. Не включайте свет, покиньте помещение, позвоните 104.',
  },
  {
    id: 5,
    categoryId: 'emergency',
    name: 'Единый экстренный',
    subcategory: 'Универсальный номер',
    phone: '112',
    address: 'Единая диспетчерская ЧР',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Единый номер для вызова всех экстренных служб. Работает без баланса.',
  },
  {
    id: 6,
    categoryId: 'emergency',
    name: 'МЧС Чечня',
    subcategory: 'Спасательные службы',
    phone: '+7 (8712) 22-30-01',
    address: 'ул. Первомайская, 19, Грозный',
    hours: 'Круглосуточно',
    website: 'https://95.mchs.gov.ru',
    district: 'Центральный',
    isEmergency: true,
    description: 'Главное управление МЧС по Чеченской Республике.',
  },

  // ── TRANSPORT ──
  {
    id: 101,
    categoryId: 'transport',
    name: 'Аэропорт «Грозный» (Северный)',
    subcategory: 'Аэропорты',
    phone: '+7 (8712) 22-60-64',
    address: 'ул. Хусейна Исаева, 1, Грозный',
    hours: 'Круглосуточно',
    website: 'https://grozny.aero',
    district: 'Северный',
    description: 'Международный аэропорт «Грозный» им. А. А. Кадырова.',
  },
  {
    id: 102,
    categoryId: 'transport',
    name: 'Железнодорожный вокзал Грозный',
    subcategory: 'Железнодорожные вокзалы',
    phone: '+7 (800) 775-00-00',
    address: 'пл. Орджоникидзе, 1, Грозный',
    hours: 'Круглосуточно',
    website: 'https://rzd.ru',
    district: 'Центральный',
    description: 'Поезда в Москву, Санкт-Петербург и другие города России.',
  },
  {
    id: 103,
    categoryId: 'transport',
    name: 'Автовокзал Грозный',
    subcategory: 'Автовокзалы',
    phone: '+7 (8712) 22-41-15',
    address: 'ул. Маяковского, 6, Грозный',
    hours: '06:00–22:00',
    district: 'Центральный',
    description: 'Автобусы в города ЧР, соседние регионы и Москву.',
  },
  {
    id: 104,
    categoryId: 'transport',
    name: 'Такси «Грозный»',
    subcategory: 'Такси',
    phone: '+7 (8712) 22-22-22',
    address: 'По всему городу',
    hours: 'Круглосуточно',
    whatsapp: '+78712222222',
    district: 'Все районы',
    description: 'Городское такси по Грозному и республике.',
  },
  {
    id: 105,
    categoryId: 'transport',
    name: 'Яндекс Go (такси)',
    subcategory: 'Такси',
    phone: '+7 (800) 600-60-07',
    address: 'По всему городу',
    hours: 'Круглосуточно',
    website: 'https://taxi.yandex.ru',
    district: 'Все районы',
    description: 'Заказ такси через приложение Яндекс Go.',
  },
  {
    id: 106,
    categoryId: 'transport',
    name: 'Маршрутное такси (диспетчерская)',
    subcategory: 'Общественный транспорт',
    phone: '+7 (8712) 22-55-10',
    address: 'ул. Богдана Хмельницкого, Грозный',
    hours: '06:00–22:00',
    district: 'Центральный',
    description: 'Информация о маршрутах и расписании маршруток по Грозному.',
  },
  {
    id: 107,
    categoryId: 'transport',
    name: 'Прокат автомобилей «АвтоЧечня»',
    subcategory: 'Аренда автомобилей',
    phone: '+7 (928) 888-11-22',
    address: 'пр. Путина, 10, Грозный',
    hours: '09:00–20:00',
    whatsapp: '+79288881122',
    district: 'Центральный',
    description: 'Аренда легковых автомобилей по Грозному и ЧР.',
  },

  // ── GOVERNMENT ──
  {
    id: 201,
    categoryId: 'government',
    name: 'МФЦ «Мои документы» — Грозный',
    subcategory: 'МФЦ',
    phone: '+7 (8712) 29-90-00',
    address: 'пр. Путина, 18, Грозный',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–18:00',
    website: 'https://mfc-chr.ru',
    district: 'Центральный',
    description: 'Государственные и муниципальные услуги: паспорта, регистрация, льготы.',
  },
  {
    id: 202,
    categoryId: 'government',
    name: 'Администрация г. Грозный',
    subcategory: 'Городская администрация',
    phone: '+7 (8712) 22-23-01',
    address: 'пл. им. А. А. Кадырова, 1, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://grozny-city.ru',
    district: 'Центральный',
    description: 'Мэрия города Грозный. Обращения граждан, городские вопросы.',
  },
  {
    id: 203,
    categoryId: 'government',
    name: 'Правительство ЧР',
    subcategory: 'Региональная власть',
    phone: '+7 (8712) 22-10-00',
    address: 'пл. им. А. А. Кадырова, 2, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    website: 'https://chechnya.gov.ru',
    district: 'Центральный',
    description: 'Официальный сайт Правительства Чеченской Республики.',
  },
  {
    id: 204,
    categoryId: 'government',
    name: 'Налоговая инспекция ФНС (УФНС по ЧР)',
    subcategory: 'Налоговые органы',
    phone: '+7 (8712) 29-88-88',
    address: 'ул. Чернышевского, 4а, Грозный',
    hours: 'Пн, Ср 08:00–18:00; Вт, Чт 08:00–20:00; Пт 08:00–16:45',
    website: 'https://nalog.gov.ru',
    district: 'Центральный',
    description: 'Налоговый учёт, ИНН, декларации, регистрация ИП.',
  },
  {
    id: 205,
    categoryId: 'government',
    name: 'Пенсионный фонд России (ЧР)',
    subcategory: 'Социальные службы',
    phone: '+7 (8712) 22-33-44',
    address: 'ул. Маяковского, 78, Грозный',
    hours: 'Пн-Пт 08:00–17:00',
    website: 'https://sfr.gov.ru',
    district: 'Центральный',
    description: 'Пенсионное обеспечение, материнский капитал, выплаты.',
  },
  {
    id: 206,
    categoryId: 'government',
    name: 'Портал Госуслуги',
    subcategory: 'Электронные услуги',
    phone: '8 (800) 100-70-10',
    address: 'Онлайн-сервис',
    hours: 'Круглосуточно',
    website: 'https://gosuslugi.ru',
    district: 'Все районы',
    description: 'Государственные и муниципальные услуги через интернет.',
  },
  {
    id: 207,
    categoryId: 'government',
    name: 'Управление коммунального хозяйства',
    subcategory: 'Коммунальные службы',
    phone: '+7 (8712) 22-44-55',
    address: 'ул. Грибоедова, 12, Грозный',
    hours: 'Пн-Пт 09:00–17:00',
    district: 'Центральный',
    description: 'Вопросы ЖКХ: отопление, водоснабжение, дороги, благоустройство.',
  },

  // ── MEDICINE ──
  {
    id: 301,
    categoryId: 'medicine',
    name: 'Республиканская клиническая больница',
    subcategory: 'Больницы',
    phone: '+7 (8712) 22-53-97',
    address: 'ул. Коминтерна, 24, Грозный',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Главная многопрофильная больница ЧР. Экстренная и плановая помощь.',
  },
  {
    id: 302,
    categoryId: 'medicine',
    name: 'Городская больница №1 Грозного',
    subcategory: 'Больницы',
    phone: '+7 (8712) 22-09-11',
    address: 'ул. Хусейна Исаева, 100, Грозный',
    hours: 'Круглосуточно',
    district: 'Северный',
    description: 'Многопрофильная городская больница. Приёмное отделение 24/7.',
  },
  {
    id: 303,
    categoryId: 'medicine',
    name: 'Детская республиканская больница',
    subcategory: 'Детские больницы',
    phone: '+7 (8712) 22-56-78',
    address: 'ул. Первомайская, 36, Грозный',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Специализированная больница для детей.',
  },
  {
    id: 304,
    categoryId: 'medicine',
    name: 'Городская поликлиника №1',
    subcategory: 'Поликлиники',
    phone: '+7 (8712) 22-10-55',
    address: 'пр. Победы, 14, Грозный',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–14:00',
    district: 'Центральный',
    description: 'Первичная медицинская помощь взрослому населению.',
  },
  {
    id: 305,
    categoryId: 'medicine',
    name: 'Городская поликлиника №3',
    subcategory: 'Поликлиники',
    phone: '+7 (8712) 22-77-33',
    address: 'ул. Маяковского, 55, Грозный',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–14:00',
    district: 'Октябрьский',
    description: 'Амбулаторная и поликлиническая помощь населению.',
  },
  {
    id: 306,
    categoryId: 'medicine',
    name: 'Аптека «Фармация» (круглосуточная)',
    subcategory: 'Аптеки',
    phone: '+7 (8712) 22-80-01',
    address: 'пр. Путина, 35, Грозный',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Круглосуточная аптека. Широкий ассортимент лекарств.',
  },
  {
    id: 307,
    categoryId: 'medicine',
    name: 'Медицинский центр «Эскулап»',
    subcategory: 'Клиники',
    phone: '+7 (928) 777-55-44',
    address: 'ул. Шейха Мансура, 20, Грозный',
    hours: 'Пн-Сб 08:00–20:00',
    whatsapp: '+79287775544',
    district: 'Центральный',
    description: 'Многопрофильная частная клиника. Консультации, УЗИ, анализы.',
  },
  {
    id: 308,
    categoryId: 'medicine',
    name: 'Стоматология «Дент»',
    subcategory: 'Стоматологии',
    phone: '+7 (928) 100-22-33',
    address: 'пр. Победы, 50, Грозный',
    hours: 'Пн-Сб 09:00–20:00',
    district: 'Центральный',
    description: 'Лечение, протезирование, имплантация зубов.',
  },

  // ── CONTACTS ──
  {
    id: 401,
    categoryId: 'contacts',
    name: 'Гостиница «Грозный Сити»',
    subcategory: 'Отели',
    phone: '+7 (8712) 28-55-00',
    address: 'пл. им. А. А. Кадырова, Грозный',
    hours: 'Круглосуточно',
    website: 'https://grozny-city-hotel.ru',
    district: 'Центральный',
    description: 'Пятизвёздочный отель в центре Грозного. Вид на башни «Грозный Сити».',
  },
  {
    id: 402,
    categoryId: 'contacts',
    name: 'Отель «Феникс»',
    subcategory: 'Отели',
    phone: '+7 (8712) 29-10-20',
    address: 'пр. Путина, 3, Грозный',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Комфортный отель в центре города. Конференц-зал, ресторан.',
  },
  {
    id: 403,
    categoryId: 'contacts',
    name: 'Сбербанк (центральный офис)',
    subcategory: 'Банки',
    phone: '8 (800) 555-55-50',
    address: 'пр. Победы, 12, Грозный',
    hours: 'Пн-Пт 09:00–19:00, Сб 10:00–16:00',
    website: 'https://sber.ru',
    district: 'Центральный',
    description: 'Кредиты, вклады, переводы, обмен валют.',
  },
  {
    id: 404,
    categoryId: 'contacts',
    name: 'ВТБ — офис Грозный',
    subcategory: 'Банки',
    phone: '8 (800) 100-24-24',
    address: 'пр. Путина, 19, Грозный',
    hours: 'Пн-Пт 09:00–19:00',
    website: 'https://vtb.ru',
    district: 'Центральный',
    description: 'Ипотека, кредиты, расчётные счета.',
  },
  {
    id: 405,
    categoryId: 'contacts',
    name: 'Нотариус Ибрагимова З.М.',
    subcategory: 'Нотариусы',
    phone: '+7 (8712) 22-91-10',
    address: 'ул. Грибоедова, 5а, Грозный',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Центральный',
    description: 'Нотариальные услуги: доверенности, завещания, договоры.',
  },
  {
    id: 406,
    categoryId: 'contacts',
    name: 'АЗС Лукойл (пр. Победы)',
    subcategory: 'АЗС',
    phone: '+7 (800) 555-00-99',
    address: 'пр. Победы, 78, Грозный',
    hours: 'Круглосуточно',
    website: 'https://lukoil.ru',
    district: 'Центральный',
    description: 'Бензин, дизель, газ. Магазин и кафе.',
  },
  {
    id: 407,
    categoryId: 'contacts',
    name: 'АЗС Роснефть (ул. Мира)',
    subcategory: 'АЗС',
    phone: '+7 (800) 200-34-76',
    address: 'пр. Мира, 44, Грозный',
    hours: 'Круглосуточно',
    district: 'Октябрьский',
    description: 'Топливо Euro-5. Программа лояльности.',
  },
  {
    id: 408,
    categoryId: 'contacts',
    name: 'Эвакуатор «Помощь на дороге»',
    subcategory: 'Эвакуаторы',
    phone: '+7 (928) 999-11-55',
    address: 'Выезд по Грозному и ЧР',
    hours: 'Круглосуточно',
    whatsapp: '+79289991155',
    district: 'Все районы',
    description: 'Эвакуация и техпомощь на дороге. Выезд за 20 минут.',
  },
  {
    id: 409,
    categoryId: 'contacts',
    name: 'Банкомат Сбер (пр. Путина)',
    subcategory: 'Банкоматы',
    phone: '8 (800) 555-55-50',
    address: 'пр. Путина, 25, Грозный',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Снятие и внесение наличных, переводы.',
  },

  // ── IMPORTANT NUMBERS ──
  {
    id: 501,
    categoryId: 'important',
    name: 'Единый экстренный (с мобильного)',
    subcategory: 'Экстренные',
    phone: '112',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Работает при нулевом балансе. Полиция, скорая, пожарные, газ.',
  },
  {
    id: 502,
    categoryId: 'important',
    name: 'Полиция',
    subcategory: 'Экстренные',
    phone: '102',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Вызов полиции.',
  },
  {
    id: 503,
    categoryId: 'important',
    name: 'Скорая помощь',
    subcategory: 'Экстренные',
    phone: '103',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Экстренная медицинская помощь.',
  },
  {
    id: 504,
    categoryId: 'important',
    name: 'Пожарная охрана',
    subcategory: 'Экстренные',
    phone: '101',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Пожар, спасение людей.',
  },
  {
    id: 505,
    categoryId: 'important',
    name: 'Аварийная газовая служба',
    subcategory: 'Экстренные',
    phone: '104',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Утечка газа.',
  },
  {
    id: 506,
    categoryId: 'important',
    name: 'МЧС Чечня',
    subcategory: 'Спасательные службы',
    phone: '+7 (8712) 22-30-01',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Чрезвычайные ситуации и катастрофы.',
  },
  {
    id: 507,
    categoryId: 'important',
    name: 'Телефон доверия (бесплатный)',
    subcategory: 'Психологическая помощь',
    phone: '8 (800) 2000-122',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    description: 'Бесплатная психологическая помощь для детей и взрослых.',
  },
  {
    id: 508,
    categoryId: 'important',
    name: 'Горячая линия Минздрава ЧР',
    subcategory: 'Здоровье',
    phone: '+7 (8712) 22-20-96',
    address: '',
    hours: 'Пн-Пт 08:00–18:00',
    district: 'Все районы',
    importantNumber: true,
    description: 'Консультации по медицинским вопросам Чеченской Республики.',
  },
];

export const districts = [
  'Все районы',
  'Центральный',
  'Октябрьский',
  'Заводской',
  'Ленинский',
  'Старопромысловский',
  'Северный',
  'Черноречье',
  'Микрорайон',
];
