export interface CityCategory {
  id: string;
  name: string;
  iconName: string;
  color: string;
  description: string;
  count: number;
}

export interface CityOrganization {
  id: number;
  categoryId: string;
  name: string;
  subcategory: string;
  phone: string;
  address: string;
  hours: string;
  website?: string;
  whatsapp?: string;
  district: string;
  isEmergency?: boolean;
  importantNumber?: boolean;
  description?: string;
  lat?: number;
  lng?: number;
}

export const cityCategories: CityCategory[] = [
  {
    id: 'emergency',
    name: 'Экстренные службы',
    iconName: 'ShieldAlert',
    color: '#FF3B30',
    description: 'Полиция, скорая, пожарные, газ',
    count: 6,
  },
  {
    id: 'transport',
    name: 'Транспорт',
    iconName: 'Car',
    color: '#007AFF',
    description: 'Аэропорты, вокзалы, такси, аренда авто',
    count: 10,
  },
  {
    id: 'government',
    name: 'Госуслуги',
    iconName: 'Landmark',
    color: '#5856D6',
    description: 'МФЦ, паспортный стол, администрация',
    count: 8,
  },
  {
    id: 'medicine',
    name: 'Медицина',
    iconName: 'HeartPulse',
    color: '#34C759',
    description: 'Больницы, клиники, аптеки',
    count: 9,
  },
  {
    id: 'contacts',
    name: 'Полезные контакты',
    iconName: 'BookMarked',
    color: '#FF9500',
    description: 'Отели, банки, нотариусы, АЗС, эвакуаторы',
    count: 12,
  },
  {
    id: 'important',
    name: 'Важные номера',
    iconName: 'Phone',
    color: '#AF52DE',
    description: 'Единые номера экстренных служб',
    count: 8,
  },
];

export const cityOrganizations: CityOrganization[] = [
  // ── EMERGENCY ──
  {
    id: 1,
    categoryId: 'emergency',
    name: 'Полиция',
    subcategory: 'Правоохранительные органы',
    phone: '102',
    address: 'Дежурная часть — по всему городу',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов полиции. При угрозе жизни или имуществу.',
  },
  {
    id: 2,
    categoryId: 'emergency',
    name: 'Скорая помощь',
    subcategory: 'Медицинские службы',
    phone: '103',
    address: 'Станция скорой помощи',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Экстренная медицинская помощь.',
  },
  {
    id: 3,
    categoryId: 'emergency',
    name: 'Пожарная охрана',
    subcategory: 'Спасательные службы',
    phone: '101',
    address: 'Пожарные части по всему городу',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Вызов пожарных. Пожар, спасение, ликвидация аварий.',
  },
  {
    id: 4,
    categoryId: 'emergency',
    name: 'Служба газа',
    subcategory: 'Коммунальные аварии',
    phone: '104',
    address: 'Аварийная газовая служба',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Утечка газа. Не включайте свет, покиньте помещение, позвоните 104.',
  },
  {
    id: 5,
    categoryId: 'emergency',
    name: 'Единый экстренный',
    subcategory: 'Универсальный номер',
    phone: '112',
    address: 'Единая диспетчерская служба',
    hours: 'Круглосуточно',
    district: 'Все районы',
    isEmergency: true,
    description: 'Единый номер для вызова всех экстренных служб.',
  },
  {
    id: 6,
    categoryId: 'emergency',
    name: 'МЧС России',
    subcategory: 'Спасательные службы',
    phone: '+7 (495) 400-99-99',
    address: 'ул. Ватутина, 1',
    hours: 'Круглосуточно',
    website: 'https://mchs.gov.ru',
    district: 'Центральный',
    isEmergency: true,
    description: 'Министерство по чрезвычайным ситуациям. Информация о катастрофах.',
  },

  // ── TRANSPORT ──
  {
    id: 101,
    categoryId: 'transport',
    name: 'Аэропорт Шереметьево',
    subcategory: 'Аэропорты',
    phone: '+7 (800) 700-75-53',
    address: 'Химки, Международное шоссе, 28А',
    hours: 'Круглосуточно',
    website: 'https://svo.aero',
    district: 'Химки',
    description: 'Крупнейший аэропорт Москвы. Терминалы B, C, D, E, F.',
  },
  {
    id: 102,
    categoryId: 'transport',
    name: 'Аэропорт Домодедово',
    subcategory: 'Аэропорты',
    phone: '+7 (495) 933-66-66',
    address: 'Домодедово, аэропорт',
    hours: 'Круглосуточно',
    website: 'https://dme.ru',
    district: 'Домодедово',
    description: 'Международный аэропорт Домодедово.',
  },
  {
    id: 103,
    categoryId: 'transport',
    name: 'Аэропорт Внуково',
    subcategory: 'Аэропорты',
    phone: '+7 (495) 937-55-55',
    address: 'Внуково, аэропорт',
    hours: 'Круглосуточно',
    website: 'https://vnukovo.ru',
    district: 'Внуково',
    description: 'Аэропорт Внуково — третий по величине аэропорт столицы.',
  },
  {
    id: 104,
    categoryId: 'transport',
    name: 'Ярославский вокзал',
    subcategory: 'Железнодорожные вокзалы',
    phone: '+7 (800) 775-00-00',
    address: 'Комсомольская площадь, 5',
    hours: 'Круглосуточно',
    website: 'https://rzd.ru',
    district: 'Центральный',
    description: 'Поезда на Ярославль, Кострому, Вологду, Архангельск, Транссиб.',
  },
  {
    id: 105,
    categoryId: 'transport',
    name: 'Казанский вокзал',
    subcategory: 'Железнодорожные вокзалы',
    phone: '+7 (800) 775-00-00',
    address: 'Комсомольская площадь, 2',
    hours: 'Круглосуточно',
    website: 'https://rzd.ru',
    district: 'Центральный',
    description: 'Поезда на Казань, Екатеринбург, Челябинск, Уфу.',
  },
  {
    id: 106,
    categoryId: 'transport',
    name: 'Яндекс Такси',
    subcategory: 'Такси',
    phone: '+7 (800) 600-60-07',
    address: 'Обслуживание по всему городу',
    hours: 'Круглосуточно',
    website: 'https://taxi.yandex.ru',
    whatsapp: '+79001234567',
    district: 'Все районы',
    description: 'Заказ такси через приложение или по телефону.',
  },
  {
    id: 107,
    categoryId: 'transport',
    name: 'Ситидрайв (каршеринг)',
    subcategory: 'Аренда автомобилей',
    phone: '+7 (499) 110-05-05',
    address: 'По всему городу',
    hours: 'Круглосуточно',
    website: 'https://citydrive.ru',
    district: 'Все районы',
    description: 'Каршеринг — аренда автомобиля поминутно без залога.',
  },
  {
    id: 108,
    categoryId: 'transport',
    name: 'Белорусский вокзал',
    subcategory: 'Железнодорожные вокзалы',
    phone: '+7 (800) 775-00-00',
    address: 'Площадь Тверской заставы, 7',
    hours: 'Круглосуточно',
    district: 'Пресненский',
    description: 'Аэроэкспресс до Шереметьево, поезда в Беларусь и Европу.',
  },
  {
    id: 109,
    categoryId: 'transport',
    name: 'Автовокзал Щёлково',
    subcategory: 'Автовокзалы',
    phone: '+7 (495) 468-04-00',
    address: 'ш. Энтузиастов, 1',
    hours: '05:00–23:00',
    district: 'Северо-Восточный',
    description: 'Автобусы в города Подмосковья и соседних регионов.',
  },
  {
    id: 110,
    categoryId: 'transport',
    name: 'Europcar (аренда авто)',
    subcategory: 'Аренда автомобилей',
    phone: '+7 (495) 771-11-00',
    address: 'Аэропорт Шереметьево, терминал D',
    hours: '08:00–22:00',
    website: 'https://europcar.ru',
    district: 'Химки',
    description: 'Международная компания аренды автомобилей.',
  },

  // ── GOVERNMENT ──
  {
    id: 201,
    categoryId: 'government',
    name: 'МФЦ «Мои документы» (Центральный)',
    subcategory: 'МФЦ',
    phone: '+7 (495) 777-77-77',
    address: 'Пресненская наб., 2',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–18:00',
    website: 'https://md.mos.ru',
    district: 'Центральный',
    description: 'Оформление паспортов, регистрации, льгот, субсидий.',
  },
  {
    id: 202,
    categoryId: 'government',
    name: 'МФЦ «Мои документы» (Юго-Западный)',
    subcategory: 'МФЦ',
    phone: '+7 (495) 777-77-77',
    address: 'пр. Вернадского, 105',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–18:00',
    website: 'https://md.mos.ru',
    district: 'Юго-Западный',
    description: 'Государственные и муниципальные услуги в удобном формате.',
  },
  {
    id: 203,
    categoryId: 'government',
    name: 'Паспортный стол ОУФМС',
    subcategory: 'Паспортные услуги',
    phone: '+7 (495) 222-48-00',
    address: 'ул. Большая Серпуховская, 11',
    hours: 'Вт, Ср, Чт 09:00–18:00',
    district: 'Центральный',
    description: 'Оформление и замена паспортов, регистрация по месту жительства.',
  },
  {
    id: 204,
    categoryId: 'government',
    name: 'Мэрия Москвы',
    subcategory: 'Городская администрация',
    phone: '+7 (495) 957-00-99',
    address: 'ул. Тверская, 13',
    hours: 'Пн-Чт 09:00–18:00, Пт 09:00–16:45',
    website: 'https://mos.ru',
    district: 'Центральный',
    description: 'Официальный сайт Мэра Москвы. Обращения граждан.',
  },
  {
    id: 205,
    categoryId: 'government',
    name: 'Портал Госуслуги',
    subcategory: 'Электронные услуги',
    phone: '8 (800) 100-70-10',
    address: 'Онлайн-сервис',
    hours: 'Круглосуточно',
    website: 'https://gosuslugi.ru',
    district: 'Все районы',
    description: 'Государственные и муниципальные услуги через интернет.',
  },
  {
    id: 206,
    categoryId: 'government',
    name: 'ГКУ «Управление коммунального хозяйства»',
    subcategory: 'Коммунальные службы',
    phone: '+7 (495) 539-53-53',
    address: 'ул. 1905 года, 10',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Пресненский',
    description: 'Вопросы ЖКХ: отопление, водоснабжение, благоустройство.',
  },
  {
    id: 207,
    categoryId: 'government',
    name: 'Налоговая инспекция №1',
    subcategory: 'Налоговые органы',
    phone: '+7 (800) 222-22-22',
    address: 'ул. Покровка, 43/2, стр. 1',
    hours: 'Пн, Ср 08:00–18:00; Вт, Чт 09:00–20:00; Пт 08:00–16:45',
    website: 'https://nalog.gov.ru',
    district: 'Центральный',
    description: 'Налоговый учёт, ИНН, сдача деклараций.',
  },
  {
    id: 208,
    categoryId: 'government',
    name: 'Пенсионный фонд России',
    subcategory: 'Социальные службы',
    phone: '8 (800) 302-20-21',
    address: 'ул. Шаболовка, 4',
    hours: 'Пн-Пт 08:00–17:00',
    website: 'https://sfr.gov.ru',
    district: 'Центральный',
    description: 'Пенсионное обеспечение, материнский капитал, выплаты.',
  },

  // ── MEDICINE ──
  {
    id: 301,
    categoryId: 'medicine',
    name: 'Городская клиническая больница №1 им. Пирогова',
    subcategory: 'Больницы',
    phone: '+7 (495) 952-62-50',
    address: 'Ленинский пр., 8',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Многопрофильная городская больница. Экстренная и плановая помощь.',
  },
  {
    id: 302,
    categoryId: 'medicine',
    name: 'Склифосовского НИИ скорой помощи',
    subcategory: 'Больницы',
    phone: '+7 (495) 625-56-37',
    address: 'Большая Сухаревская площадь, 3',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Ведущий центр экстренной медицинской помощи России.',
  },
  {
    id: 303,
    categoryId: 'medicine',
    name: 'Городская поликлиника №19',
    subcategory: 'Поликлиники',
    phone: '+7 (499) 246-29-98',
    address: 'ул. Полянка, 2/10',
    hours: 'Пн-Пт 08:00–20:00, Сб 09:00–15:00',
    district: 'Центральный',
    description: 'Первичная медицинская помощь взрослому населению.',
  },
  {
    id: 304,
    categoryId: 'medicine',
    name: 'Детская городская больница №13 им. Филатова',
    subcategory: 'Детские больницы',
    phone: '+7 (499) 254-57-35',
    address: 'ул. Садовая-Кудринская, 15',
    hours: 'Круглосуточно',
    district: 'Пресненский',
    description: 'Многопрофильный детский стационар.',
  },
  {
    id: 305,
    categoryId: 'medicine',
    name: 'Аптека «Горздрав»',
    subcategory: 'Аптеки',
    phone: '+7 (495) 730-70-90',
    address: 'ул. Тверская, 25',
    hours: '08:00–22:00',
    website: 'https://gorzdrav.org',
    district: 'Центральный',
    description: 'Широкий ассортимент лекарств. Доставка на дом.',
  },
  {
    id: 306,
    categoryId: 'medicine',
    name: 'Аптека «Апрель» (круглосуточная)',
    subcategory: 'Аптеки',
    phone: '+7 (495) 789-99-11',
    address: 'ул. Арбат, 12',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Круглосуточная аптека с широким ассортиментом.',
  },
  {
    id: 307,
    categoryId: 'medicine',
    name: 'Медицинский центр «СМ-Клиника»',
    subcategory: 'Клиники',
    phone: '+7 (495) 777-48-49',
    address: 'ул. Ярцевская, 8',
    hours: 'Пн-Сб 08:00–21:00, Вс 09:00–20:00',
    website: 'https://smclinic.ru',
    district: 'Западный',
    description: 'Многопрофильная клиника. Консультации, диагностика, лечение.',
  },
  {
    id: 308,
    categoryId: 'medicine',
    name: 'МЕДСИ (клиника)',
    subcategory: 'Клиники',
    phone: '+7 (495) 023-60-84',
    address: 'Грузинский пер., 3А',
    hours: 'Ежедневно 07:00–21:00',
    website: 'https://medsi.ru',
    district: 'Пресненский',
    description: 'Сеть современных медицинских клиник.',
  },
  {
    id: 309,
    categoryId: 'medicine',
    name: 'Стоматология «Дент-Люкс»',
    subcategory: 'Стоматологии',
    phone: '+7 (495) 111-22-33',
    address: 'Ленинградский пр., 60',
    hours: 'Пн-Пт 09:00–21:00, Сб-Вс 10:00–18:00',
    district: 'Северный',
    description: 'Современная стоматология. Лечение, протезирование, имплантация.',
  },

  // ── CONTACTS ──
  {
    id: 401,
    categoryId: 'contacts',
    name: 'Отель «Метрополь»',
    subcategory: 'Отели',
    phone: '+7 (495) 501-91-00',
    address: 'Театральный проезд, 2',
    hours: 'Круглосуточно',
    website: 'https://metropol-moscow.ru',
    district: 'Центральный',
    description: 'Легендарный исторический отель в центре Москвы.',
  },
  {
    id: 402,
    categoryId: 'contacts',
    name: 'Сбербанк (отделение центральное)',
    subcategory: 'Банки',
    phone: '8 (800) 555-55-50',
    address: 'ул. Новый Арбат, 21',
    hours: 'Пн-Пт 09:00–20:00, Сб 10:00–18:00',
    website: 'https://sber.ru',
    district: 'Центральный',
    description: 'Полный спектр банковских услуг. Кредиты, вклады, переводы.',
  },
  {
    id: 403,
    categoryId: 'contacts',
    name: 'ВТБ (отделение)',
    subcategory: 'Банки',
    phone: '8 (800) 100-24-24',
    address: 'ул. Тверская, 22',
    hours: 'Пн-Пт 09:00–19:00',
    website: 'https://vtb.ru',
    district: 'Центральный',
    description: 'Банк ВТБ — ипотека, кредиты, расчётные счета.',
  },
  {
    id: 404,
    categoryId: 'contacts',
    name: 'Банкомат Сбер (Арбат)',
    subcategory: 'Банкоматы',
    phone: '8 (800) 555-55-50',
    address: 'ул. Арбат, 15',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Снятие и внесение наличных, переводы.',
  },
  {
    id: 405,
    categoryId: 'contacts',
    name: 'Нотариус Иванова М.А.',
    subcategory: 'Нотариусы',
    phone: '+7 (495) 777-55-11',
    address: 'Бульварное кольцо, Чистопрудный б-р, 10',
    hours: 'Пн-Пт 09:00–18:00',
    district: 'Центральный',
    description: 'Нотариальные услуги: доверенности, завещания, договоры.',
  },
  {
    id: 406,
    categoryId: 'contacts',
    name: 'АЗС Лукойл (Кутузовский)',
    subcategory: 'АЗС',
    phone: '+7 (800) 555-00-99',
    address: 'Кутузовский пр., 34',
    hours: 'Круглосуточно',
    website: 'https://lukoil.ru',
    district: 'Западный',
    description: 'Бензин, дизель, газ. Магазин и кафе.',
  },
  {
    id: 407,
    categoryId: 'contacts',
    name: 'АЗС Газпромнефть',
    subcategory: 'АЗС',
    phone: '+7 (800) 707-49-49',
    address: 'Ленинградское ш., 78',
    hours: 'Круглосуточно',
    website: 'https://opti.gazpromneft.ru',
    district: 'Северный',
    description: 'Топливо Euro-5. Программа лояльности «Нам По Пути».',
  },
  {
    id: 408,
    categoryId: 'contacts',
    name: 'Эвакуатор «Быстро»',
    subcategory: 'Эвакуаторы',
    phone: '+7 (495) 999-11-22',
    address: 'Круглосуточный выезд по Москве и МО',
    hours: 'Круглосуточно',
    whatsapp: '+74959991122',
    district: 'Все районы',
    description: 'Эвакуация легковых и грузовых автомобилей. Выезд за 20 минут.',
  },
  {
    id: 409,
    categoryId: 'contacts',
    name: 'Эвакуатор ГИБДД',
    subcategory: 'Эвакуаторы',
    phone: '+7 (495) 617-70-35',
    address: 'Ул. Стромынка, 13',
    hours: 'Круглосуточно',
    district: 'Сокольники',
    description: 'Штрафстоянка ГИБДД. Возврат эвакуированных автомобилей.',
  },
  {
    id: 410,
    categoryId: 'contacts',
    name: 'Marriott Tverskaya (отель)',
    subcategory: 'Отели',
    phone: '+7 (495) 937-00-00',
    address: '1-я Тверская-Ямская ул., 34',
    hours: 'Круглосуточно',
    website: 'https://marriott.com',
    district: 'Тверской',
    description: 'Международная сеть отелей. Конференц-залы, спа, ресторан.',
  },
  {
    id: 411,
    categoryId: 'contacts',
    name: 'Нотариус Петров В.С.',
    subcategory: 'Нотариусы',
    phone: '+7 (495) 632-44-55',
    address: 'Большая Пироговская ул., 7',
    hours: 'Пн-Пт 10:00–19:00, Сб 10:00–15:00',
    district: 'Хамовники',
    description: 'Все виды нотариальных действий. Запись по телефону.',
  },
  {
    id: 412,
    categoryId: 'contacts',
    name: 'Банкомат ВТБ (Лубянка)',
    subcategory: 'Банкоматы',
    phone: '8 (800) 100-24-24',
    address: 'Большая Лубянка, 3',
    hours: 'Круглосуточно',
    district: 'Центральный',
    description: 'Снятие, внесение наличных, переводы между счетами.',
  },

  // ── IMPORTANT NUMBERS ──
  {
    id: 501,
    categoryId: 'important',
    name: 'Единый экстренный (с мобильного)',
    subcategory: 'Экстренные',
    phone: '112',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Работает при нулевом балансе. Полиция, скорая, пожарные, газ.',
  },
  {
    id: 502,
    categoryId: 'important',
    name: 'Полиция',
    subcategory: 'Экстренные',
    phone: '102',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Вызов полиции.',
  },
  {
    id: 503,
    categoryId: 'important',
    name: 'Скорая помощь',
    subcategory: 'Экстренные',
    phone: '103',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Экстренная медицинская помощь.',
  },
  {
    id: 504,
    categoryId: 'important',
    name: 'Пожарная охрана',
    subcategory: 'Экстренные',
    phone: '101',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Пожар, спасение людей.',
  },
  {
    id: 505,
    categoryId: 'important',
    name: 'Аварийная газовая служба',
    subcategory: 'Экстренные',
    phone: '104',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    isEmergency: true,
    description: 'Утечка газа.',
  },
  {
    id: 506,
    categoryId: 'important',
    name: 'Телефон доверия',
    subcategory: 'Психологическая помощь',
    phone: '8 (800) 2000-122',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    description: 'Бесплатная психологическая помощь для детей и взрослых.',
  },
  {
    id: 507,
    categoryId: 'important',
    name: 'Горячая линия Минздрава',
    subcategory: 'Здоровье',
    phone: '8 (800) 200-03-89',
    address: '',
    hours: 'Пн-Пт 08:00–20:00',
    district: 'Все районы',
    importantNumber: true,
    description: 'Консультации по вопросам здоровья и медицинской помощи.',
  },
  {
    id: 508,
    categoryId: 'important',
    name: 'Антикоррупционная горячая линия',
    subcategory: 'Госуправление',
    phone: '8 (800) 100-80-07',
    address: '',
    hours: 'Круглосуточно',
    district: 'Все районы',
    importantNumber: true,
    description: 'Сообщить о коррупции в органах власти.',
  },
];

export const districts = [
  'Все районы',
  'Центральный',
  'Северный',
  'Северо-Восточный',
  'Восточный',
  'Юго-Восточный',
  'Южный',
  'Юго-Западный',
  'Западный',
  'Северо-Западный',
  'Пресненский',
  'Тверской',
  'Хамовники',
  'Сокольники',
  'Химки',
  'Домодедово',
  'Внуково',
];
