import type { AutoPartsSupplierImportInput } from "@shared/auto-parts-schema";

const GROZNY_FOREIGN = "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok";
const GROZNY_ACCESSORIES = "https://mestam.info/ru/groznii/avtoaksessuari";
const ARGUN_PARTS = "https://argun.spravker.ru/avtozapchasti/";
const ARGUN_DISMANTLERS = "https://argun.spravker.ru/avtorazbor-inomarok/";
const GUDERMES_FOREIGN = "https://mestam.info/ru/gudermes/avtozapchasti-dlya-inomarok";
const URUS_PARTS = "https://urus-martan.spravker.ru/avtozapchasti/";
const URUS_DISMANTLERS = "https://urus-martan.spravker.ru/avtorazborki/";
const URUS_KIA = "https://oskarkuchera.ru/urus-martan";

export const curatedChechnyaAutoPartsSeeds: AutoPartsSupplierImportInput[] = [
  {
    sourceName: "public-directory",
    sourceExternalId: "grozny-exist-chervlennaya-2a",
    sourceUrl: "https://chit-kody.ru/groznyj",
    data: {
      name: "Exist.ru",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Червленная улица, 2А",
      phone: "+7 928 948-71-17",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "public-directory",
    sourceExternalId: "grozny-daimzap-neftyanik-1-line",
    sourceUrl: "https://pk-kondor.ru/groznyj",
    data: {
      name: "DaimZap",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "СТ Нефтяник, 1-я линия",
      phone: "+7 928 022-21-40",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-toyota-grozny-argun-11zh",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "TOYOTA",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "трасса Грозный-Аргун, 11ж",
      phone: "+7 930 666-67-63",
      brands: ["Toyota"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-focus-kadyrova-10",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "ФОКУС",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Рамзана Кадырова, 10",
      phone: "+7 929 008-97-97",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-ertin-motors-petropavlovskiy-44-2",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "Ertin Motors",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "2-й переулок Петропавловского шоссе, 44/2",
      phone: "+7 920 774-80-90",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-daytona-petropavlovskoe-22-1",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "Daytona",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Петропавловское шоссе, 22/1",
      phone: "+7 928 085-77-42",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-avtoritet-irtyshskaya-2",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "Авторитет",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Иртышская улица, 2",
      phone: "+7 965 961-40-15",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-trek-uzueva-89a",
    sourceUrl: GROZNY_FOREIGN,
    data: {
      name: "Trek",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Узуева, 89а",
      phone: "+7 928 736-05-30",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJ6QS50unTUUAR1qhtY_Sadcg",
    data: {
      name: "Автозапчасти «Самара» на Гурина",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Маты Кишиевой, 103",
      phone: "+7 928 896-37-63",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJq5daQ07RUUARvB8XvERKTXs",
    data: {
      name: "Автомагазин «КАЛИНА»",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "проспект Бульвар Дудаева, 1а",
      phone: "+7 928 787-78-80",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJAa-Wo1bRUUARgFHw03x-ACU",
    data: {
      name: "Автомагазин MUSTANG",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "проспект Мохаммеда Али, 2",
      phone: "+7 928 889-33-00",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJqxe4Y07RUUARxf7lqTVlGvU",
    data: {
      name: "BRABUS",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Умара Садаева, 1",
      phone: "+7 928 739-79-78",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJj3dI_IvVUUARsTuSYe2w1t0",
    data: {
      name: "Автомагазин Приора",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Сайханова, 47",
      phone: "+7 928 738-45-12",
      brands: ["Lada"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-avto-parts-95-lermontova-129",
    sourceUrl: GROZNY_ACCESSORIES,
    data: {
      name: "AVTO PARTS 95",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Лермонтова, 129",
      phone: "+7 928 488-38-38",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJ-2awqv_RUUAR5D5or0MIMqg",
    data: {
      name: "Авторазбор Тойота",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Машинная улица, 3",
      phone: "+7 963 589-11-30",
      brands: ["Toyota"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJ202GQevRUUARi_7xKJOeY9U",
    data: {
      name: "Разбор Поло",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Закревского, 4",
      brands: ["Volkswagen"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJSZDc7EHVT0ARj49bv0LLF5s",
    data: {
      name: "Авторазбор Мерседес Бенц",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Узуева, 94",
      phone: "+7 928 782-16-85",
      brands: ["Mercedes-Benz"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJwQGnUxzTUUAR1T1RjJnic0g",
    data: {
      name: "BMW RAZBOR 95",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Абульяна",
      phone: "+7 928 475-70-00",
      brands: ["BMW"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "grozny-kamaz-razbor-aldy",
    sourceUrl: "https://argun.spravker.ru/avtorazbor-iaponskikh-avtomobilei/",
    data: {
      name: "КАМАЗ разбор",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "посёлок Алды, Шейх-Мансуровский район",
      phone: "+7 929 899-93-12",
      brands: ["КАМАЗ"],
      partGroups: [],
      vehicleTypes: ["truck"],
      vehicleOrigins: ["domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "argun-exist-shosseynaya-111",
    sourceUrl: ARGUN_PARTS,
    data: {
      name: "Exist.ru",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Аргун",
      address: "Шоссейная улица, 111",
      phone: "+7 928 946-71-17",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "argun-pit-stop-dudaeva-1a",
    sourceUrl: ARGUN_PARTS,
    data: {
      name: "Пит Стоп",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Аргун",
      address: "улица Дудаева, 1А",
      phone: "+7 938 000-23-62",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "argun-infiniti-shosseynaya-110v",
    sourceUrl: ARGUN_PARTS,
    data: {
      name: "Инфинити",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Аргун",
      address: "Шоссейная улица, 110В",
      phone: "+7 938 015-91-11",
      brands: ["Infiniti"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "argun-avtomagazin-osmanova-2",
    sourceUrl: ARGUN_PARTS,
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Аргун",
      address: "улица М. Османова, 2",
      phone: "+7 929 000-00-96",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "argun-vag-audi-kadyrova-111",
    sourceUrl: ARGUN_PARTS,
    data: {
      name: "Vag audi",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Аргун",
      address: "улица А.А. Кадырова, 111",
      brands: ["Volkswagen", "Audi"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "mesker-yurt-gold-argunskaya-40",
    sourceUrl: ARGUN_DISMANTLERS,
    data: {
      name: "Gold",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Мескер-Юрт",
      address: "Аргунская улица, 40",
      phone: "+7 928 000-76-78",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "djalka-auto-razbor-mamakaeva",
    sourceUrl: ARGUN_DISMANTLERS,
    data: {
      name: "Авторазбор",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Джалка",
      address: "улица М.А. Мамакаева",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-umarova-23",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "Магазин автозапчастей",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "улица Умарова, 23",
      phone: "+7 928 649-99-44",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-detal-r217-688-1",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "Деталь",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "Р-217, 688-й километр, 1",
      phone: "+7 989 178-11-11",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-111-kirova-66a",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "111",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "улица Кирова, 66а",
      phone: "+7 928 735-07-26",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-charto-amirova-3a",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "Чарто",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "улица Амирова, 3а",
      phone: "+7 928 781-28-12",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-samara-hataeva-25a",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "Самара",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "переулок Хатаева, 25а",
      phone: "+7 928 740-08-18",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "gudermes-lider-titova-144",
    sourceUrl: GUDERMES_FOREIGN,
    data: {
      name: "Лидер",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "улица Титова, 144",
      phone: "+7 928 782-87-87",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "public-directory",
    sourceExternalId: "gudermes-toyota-parts-taysumova-27",
    sourceUrl: "https://oskarkuchera.ru/gudermes",
    data: {
      name: "Toyota Parts",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Гудермес",
      address: "улица Тайсумова, 27",
      phone: "+7 922 698-21-55",
      brands: ["Toyota"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "gudermes-best-auto-95",
    sourceUrl: ARGUN_DISMANTLERS,
    data: {
      name: "Best-Auto 95",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Гудермес",
      address: "Гудермес",
      phone: "+7 928 011-39-39",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-vaz-gaz-sheripova-68",
    sourceUrl: URUS_PARTS,
    data: {
      name: "Ваз-Газ",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "улица А. Шерипова, 68",
      phone: "+7 928 087-12-54",
      brands: ["Lada", "ГАЗ"],
      partGroups: [],
      vehicleTypes: ["passenger", "truck"],
      vehicleOrigins: ["domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-lecar-usamova-1b",
    sourceUrl: URUS_PARTS,
    data: {
      name: "Lecar Store",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "улица Нурди Усамова, 1Б",
      phone: "+7 925 891-88-01",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger", "truck"],
      vehicleOrigins: ["foreign", "domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-lada-detail-sportivnaya-132",
    sourceUrl: URUS_PARTS,
    data: {
      name: "Lada Dеталь",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "Спортивная улица, 132",
      brands: ["Lada"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-sulim-lomonosova-121",
    sourceUrl: URUS_PARTS,
    data: {
      name: "Сулим",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "улица Ломоносова, 121",
      phone: "+7 928 888-82-62",
      brands: [],
      partGroups: [],
      vehicleTypes: ["truck"],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-autodetal-usamova",
    sourceUrl: URUS_PARTS,
    data: {
      name: "АвтоДеталь",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "улица Нурди Усамова",
      phone: "+7 928 477-22-02",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "public-directory",
    sourceExternalId: "urus-kia-badueva-72-2",
    sourceUrl: URUS_KIA,
    data: {
      name: "Kia. Urus",
      supplierType: "store",
      partsCondition: "used",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "улица С. Бадуева, 72/2",
      phone: "+7 938 017-99-06",
      brands: ["Kia"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "urus-bitstop-aprelskaya-54",
    sourceUrl: URUS_DISMANTLERS,
    data: {
      name: "Bitstop",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Урус-Мартан",
      address: "Апрельская улица, 54",
      phone: "8 800 600-91-67",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravbiz",
    sourceExternalId: "shali-irs-auto-kadyrova",
    sourceUrl: "https://spravbiz.ru/shali/avto/avtomagaziny/",
    data: {
      name: "Ирс Авто",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Шали",
      address: "улица А.Х. Кадырова",
      phone: "+7 962 655-45-03",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign", "domestic"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "google-business",
    sourceExternalId: "ChIJN0KTWmItTkAR42A_3xMeGZA",
    data: {
      name: "Разбор Toyota Camry Corolla",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Шали",
      address: "Луговая улица",
      phone: "+7 963 589-11-30",
      brands: ["Toyota"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-uzueva-138b",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Магазин автозапчастей",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Узуева, 138Б",
      phone: "+7 995 000-02-19",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-abdally-4",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Абдаллы 2 Бен Аль-Хусейна, 4",
      phone: "+7 928 087-69-06",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-r217-18-965",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Магазин автозапчастей для иномарок",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "трасса Р-217, 18, 2 этаж",
      phone: "+7 965 999-97-86",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-arzamasskaya-1",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Магазин автозапчастей",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Арзамасская улица, 1",
      phone: "+7 928 944-61-67",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-kunta-hadji-145-1",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "проспект Кунта-Хаджи Кишиева, 145/1",
      phone: "+7 928 085-80-73",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-derzhavina-405",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Державина, 405",
      phone: "+7 928 000-03-26",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-verkhnyaya-2v",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Верхняя улица, 2в",
      phone: "+7 928 089-65-73",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-spa-avto-ismailova-30",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Spa avto",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Э.Э. Исмаилова, 30, 2 этаж",
      phone: "+7 928 642-04-04",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-nazarbaeva-117g",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "улица Нурсултана Назарбаева, 117г",
      phone: "+7 928 269-34-04",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-vostochnaya-15-1",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Автомагазин",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Восточная объездная, 15/1",
      phone: "+7 963 989-31-21",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-shansol-kommunisticheskaya-60",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Шансоль-торг",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Коммунистическая улица, 60",
      phone: "+7 928 000-97-99",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "mestam.info",
    sourceExternalId: "grozny-store-ellada-assinovskaya-9g",
    sourceUrl: "https://mestam.info/ru/groznii/avtozapchasti-dlya-inomarok",
    data: {
      name: "Эллада",
      supplierType: "store",
      partsCondition: "new",
      salesType: "retail",
      city: "Грозный",
      address: "Ассиновская улица, 9г",
      phone: "+7 928 086-96-38",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-center-ozernaya-41",
    sourceUrl: "https://2gis.ru/grozny/search/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80/rubricId/406",
    data: {
      name: "Центр авторазбора",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Озёрная улица, 41",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: [],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-toyota-grozny-mashinnaya-5-4",
    sourceUrl: "https://2gis.ru/grozny/search/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80/rubricId/406",
    data: {
      name: "Toyota-Grozny.ru",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Машинная улица, 5/4",
      brands: ["Toyota"],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-95-mukhadi-dadaeva-198",
    sourceUrl: "https://2gis.ru/grozny/firm/70000001102247218",
    data: {
      name: "Авторазбор 95",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Мухади Дадаева, 198",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-chervlennaya-2v",
    sourceUrl: "https://2gis.ru/grozny/search/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80/rubricId/406",
    data: {
      name: "Автомагазин — авторазбор",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Червленная улица, 2в",
      brands: [],
      partGroups: [],
      vehicleTypes: [],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-altayskaya-1a-k2",
    sourceUrl: "https://2gis.ru/grozny/geo/16185446848312751",
    data: {
      name: "Мастерская по авторазбору",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Алтайская улица, 1а к2",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-pobedy-5a",
    sourceUrl: "https://2gis.ru/grozny/firm/70000001112389567",
    data: {
      name: "Компания по авторазбору",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Победы, 5а",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "2gis",
    sourceExternalId: "grozny-dismantler-vahi-alieva-8b-1",
    sourceUrl: "https://2gis.ru/grozny/search/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80/rubricId/406",
    data: {
      name: "Мастерская по авторазбору",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Вахи Алиева, 8Б/1",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "grozny-dismantler-ashar-auto-rozy-luxemburg-3",
    sourceUrl: "https://groznyi.spravker.ru/avtorazbor-inomarok/",
    data: {
      name: "Ashar-auto",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Розы Люксембург, 3",
      phone: "+7 964 904-78-95",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "grozny-dismantler-sto-derbentskaya-30",
    sourceUrl: "https://groznyi.spravker.ru/avtorazbor-inomarok/",
    data: {
      name: "СТО — авторазбор",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Дербентская улица, 30",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "grozny-dismantler-ozernaya-19",
    sourceUrl: "https://groznyi.spravker.ru/avtorazbor-inomarok/",
    data: {
      name: "Авторазбор",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "Озёрная улица, 19",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },
  {
    sourceName: "spravker",
    sourceExternalId: "grozny-dismantler-avtoliga-visaitova-100",
    sourceUrl: "https://groznyi.spravker.ru/avtorazborki/masterskaia-po-avtorazboru.htm",
    data: {
      name: "Автолига",
      supplierType: "dismantler",
      partsCondition: "used",
      salesType: "retail",
      city: "Грозный",
      address: "улица Висаитова, 100",
      phone: "+7 928 018-88-95",
      brands: [],
      partGroups: [],
      vehicleTypes: ["passenger"],
      vehicleOrigins: ["foreign"],
      delivery: false,
      pickup: true,
      verified: false,
    },
  },

];
