import { useMemo, useState } from "react";
import { Database, RefreshCw, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { categoryPayloadSchema } from "@shared/category-schema";
import type { Category } from "@shared/schema";
import { useAdminData, useAdminRuntime } from "./admin-runtime";
import { AdminEditor, AdminPageList, AdminToolbar, LoadState, StatusBadge, EmptyList } from "./admin-common";
import type { ImportConfig, ImportRun, AuditEntry } from "./admin-types";
const iconLabels: Record<string, string> = { Wrench: "Инструмент", Zap: "Электрика", Sparkles: "Уборка", Hammer: "Ремонт", Palette: "Красота", Car: "Авто", Package: "Доставка", BookOpen: "Обучение" };
export function AdminCategories() {
  const data = useAdminData<Category[]>("/api/admin/categories"); const [q, setQ] = useState(""); const [edit, setEdit] = useState<Category | "new" | null>(null); const { clearMessage, busy } = useAdminRuntime();
  const items = useMemo(() => (data.data ?? []).filter(c => c.name.toLocaleLowerCase("ru-RU").includes(q.trim().toLocaleLowerCase("ru-RU"))), [data.data, q]);
  return <><AdminToolbar value={q} onChange={setQ} placeholder="Название категории" onAdd={() => { clearMessage(); setEdit("new"); }} addLabel="Добавить категорию" /><LoadState query={data}><AdminPageList items={items} render={c => <article className="admin-record" key={c.id}><div className="admin-record-avatar" aria-hidden="true">{c.emoji}</div><div className="admin-record-info"><h2>{c.name}</h2><p>#{c.id} · {iconLabels[c.iconName] ?? c.iconName}</p></div><Button variant="outline" disabled={busy} onClick={e => { e.currentTarget.focus(); clearMessage(); setEdit(c); }}><Pencil size={16} className="mr-2" />Изменить</Button></article>} /></LoadState>{edit && <CategoryEditor item={edit === "new" ? null : edit} onClose={() => setEdit(null)} />}</>;
}
function CategoryEditor({ item, onClose }: { item: Category | null; onClose: () => void }) {
  const { act } = useAdminRuntime(); const [form, setForm] = useState({ name: item?.name ?? "", iconName: item?.iconName ?? "Wrench", emoji: item?.emoji ?? "🔧", color: item?.color ?? "#0B8FB6" });
  return <AdminEditor title={item ? "Изменить категорию" : "Новая категория"} description="Название будет использовано в поиске и фильтрах каталога." value={form} onClose={onClose} onSave={async () => { const p = categoryPayloadSchema.safeParse(form); if (!p.success) throw new Error("Проверьте название, значок, эмодзи и цвет категории."); return act(`/api/admin/categories${item ? `/${item.id}` : ""}`, item ? "PUT" : "POST", p.data); }}>
    <label className="admin-field">Название<input required minLength={2} maxLength={80} value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} /></label><label className="admin-field">Значок<select value={form.iconName} onChange={e => setForm(f => ({ ...f, iconName: e.target.value }))}>{Object.entries(iconLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label className="admin-field">Эмодзи<input value={form.emoji} maxLength={12} onChange={e => setForm(f => ({ ...f, emoji: e.target.value }))} /></label><label className="admin-field">Цвет<input type="color" value={form.color} onChange={e => setForm(f => ({ ...f, color: e.target.value }))} /></label>
  </AdminEditor>;
}
const runLabels: Record<string, string> = { running: "Выполняется", success: "Завершён", partial: "Частично", failed: "Ошибка" };
export function AdminImports() {
  const config = useAdminData<ImportConfig>("/api/admin/import/config"); const runs = useAdminData<ImportRun[]>("/api/admin/import/runs?limit=30"); const { act, busy } = useAdminRuntime();
  const start = (sourceName?: string) => act("/api/admin/import/run", "POST", sourceName ? { sourceName } : {}, sourceName ? `Запустить импорт из «${sourceName}»? Данные каталога будут обновлены; ручные исправления сохраняются.` : "Запустить все настроенные источники импорта? Это обновит данные каталога.", "Запрос выполнен. Проверьте результат в истории запусков.");
  return <div className="admin-section-body"><div className="admin-notice">Источники настраиваются на сервере. Панель не показывает ключи и не позволяет вводить произвольные адреса для импорта. Ручные исправления имеют приоритет.</div><LoadState query={config}>
    {config.data?.configurationError && <div role="alert" className="admin-error">Ошибка конфигурации: {config.data.configurationError}</div>}
    <div className="admin-record"><div className="admin-record-info"><h2>Автоматическое обновление</h2><p>{config.data?.enabled ? `Включено · каждые ${config.data.intervalMinutes} мин` : "Выключено"}</p><p>Настроено источников: {config.data?.sources.length ?? "—"}</p></div><div className="admin-record-actions"><Button variant="outline" disabled={busy} onClick={() => void act("/api/admin/import/reload", "POST", undefined, "Перечитать конфигурацию источников с сервера?", "Конфигурация перечитана")}><RefreshCw size={16} className="mr-2" />Перечитать</Button><Button disabled={busy || !config.data?.sources.some(s => s.enabled)} onClick={() => void start()}><Database size={16} className="mr-2" />Запустить все</Button></div></div>
    <div className="admin-record-list">{config.data?.sources.map(s => <article className="admin-record" key={s.name}><div className="admin-record-info"><h2>{s.name}</h2><p>Формат {s.adapter.toUpperCase()} · до {s.maxItems} записей</p><StatusBadge value={s.enabled ? "visible" : "hidden"} label={s.enabled ? "Включён" : "Выключен"} /></div><Button variant="outline" disabled={busy || !s.enabled} onClick={() => void start(s.name)}>Запустить</Button></article>)}</div>{!config.data?.sources.length && <EmptyList>Источники не настроены. Их конфигурация задаётся администратором сервера.</EmptyList>}
    </LoadState><h2 className="admin-section-title">Последние 30 запусков</h2><LoadState query={runs}><div className="admin-record-list">{runs.data?.map(r => <article className="admin-record" key={r.id}><div className="admin-record-info"><div className="admin-badges"><h3>{r.sourceName}</h3><StatusBadge value={r.status} label={runLabels[r.status]} /></div><p>{new Date(r.startedAt).toLocaleString("ru-RU")} · {r.trigger === "admin" ? "Ручной запуск" : r.trigger === "scheduler" ? "По расписанию" : "При старте сервера"}</p><p>Получено: {r.fetched} · Импортировано: {r.imported} · Пропущено: {r.skipped}</p>{!!r.errors.length && <details><summary className="text-sm font-semibold">Ошибки ({r.errors.length})</summary>{r.errors.map((message, i) => <p key={i}>{message}</p>)}</details>}</div></article>)}</div>{!runs.data?.length && <EmptyList>Запусков пока нет.</EmptyList>}</LoadState></div>;
}
const actionLabels: Record<string, string> = { "provider.create": "Создан профиль", "provider.update": "Изменён профиль", "provider.hide": "Профиль скрыт", "provider.show": "Профиль опубликован", "provider.verification": "Изменён статус проверки", "provider.verification_review": "Принято решение по документам", "category.create": "Создана категория", "category.update": "Изменена категория", "auto_parts.create": "Добавлен магазин", "auto_parts.update": "Изменён магазин", "auto_parts.hide": "Магазин скрыт", "auto_parts.show": "Магазин опубликован", "auto_parts.owner": "Изменён владелец магазина", "admin.bootstrap": "Назначен администратор", "directory.doctor.create": "Добавлен врач", "directory.doctor.update": "Изменён врач", "directory.doctor.hide": "Врач скрыт", "directory.doctor.show": "Врач опубликован", "directory.city_service.create": "Добавлена организация", "directory.city_service.update": "Изменена организация", "directory.city_service.hide": "Организация скрыта", "directory.city_service.show": "Организация опубликована", "import.run": "Запуск импорта", "import.reload": "Перечитана конфигурация" };
export function AdminAudit() {
  const data = useAdminData<AuditEntry[]>("/api/admin/audit?limit=200"); const [q, setQ] = useState("");
  const items = useMemo(() => (data.data ?? []).filter(e => `${e.action} ${actionLabels[e.action] ?? ""} ${e.entityId} ${e.adminName ?? ""}`.toLocaleLowerCase("ru-RU").includes(q.trim().toLocaleLowerCase("ru-RU"))), [data.data, q]);
  return <><div className="admin-notice">Последние 200 событий, от новых к старым. Записи журнала из панели изменить или удалить нельзя.</div><AdminToolbar value={q} onChange={setQ} placeholder="Действие, администратор или ID записи" /><LoadState query={data}><AdminPageList items={items} render={e => <article key={e.id} className="admin-record"><div className="admin-record-info"><h2>{actionLabels[e.action] ?? e.action}</h2><p>{e.adminName || "Система"} · Запись #{e.entityId}</p><p>{new Date(e.createdAt).toLocaleString("ru-RU")}</p><details className="mt-2"><summary className="text-xs font-semibold">Подробности события</summary><pre className="admin-audit-detail">{JSON.stringify(e.details, null, 2)}</pre></details></div></article>} /></LoadState></>;
}
